name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # يشتغل كل يوم الساعة 00:00 UTC
  workflow_dispatch:       # تشغيل يدوي من Actions

permissions:
  contents: write   # عشان يقدر يعمل push على الفرع

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: yousef-absamad
          outputs: dist/snake.svg

      - name: Commit and Push Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add dist/snake.svg
          git commit -m "chore: update snake animation" || echo "No changes to commit"
          git push origin output --force
